CREATE TABLE LOAN (
  ID INT PRIMARY KEY,
  DEBTOR VARCHAR(50) NOT NULL,
  LENDED_AMOUNT DECIMAL(12,2) NOT NULL,
  REQUIRED_AMOUNT DECIMAL(12,2) NOT NULL,
  INTEREST DECIMAL(5,2) NOT NULL
);

CREATE TABLE INVESTMENT (
  ID INT PRIMARY KEY,
  INVESTOR VARCHAR(50) NOT NULL,
  INITIAL_AMOUNT DECIMAL(12,2) NOT NULL,
  REMAINING_AMOUNT DECIMAL(12,2) NOT NULL
);

CREATE TABLE LENDING(
  LOAN_ID INT,
  INVESTMENT_ID INT,
  AMOUNT DECIMAL(12,2) NOT NULL,
  INTEREST DECIMAL(5,2) NOT NULL
);